version: "3.9"

services:
  oriochat:
    build: ./
    image: oriochat-client-image
    container_name: oriochat-client-container
    ports:
      - 3000:3000
    environment:
      - VITE_API_ENDPOINT=http://localhost:8090/
      - VITE_SOCKET_ENDPOINT=http://localhost:8092/

    networks:
      - oriochat-network

networks:
  oriochat-network:
    name: oriochat-network
    driver: bridge
