version: "3.9"

services:
  oriochat:
    build: ./
    image: oriochat-client-image
    container_name: oriochat-client-container
    ports:
      - 3000:3000
    environment:
      - VITE_USER_SERVICE_API_ENDPOINT=http://4.204.71.173:5000/
      - VITE_CHAT_SERVICE_API_ENDPOINT=http://4.204.71.173:8090/
      - VITE_SOCKET_ENDPOINT=http://4.204.71.173:8092/

    networks:
      - oriochat-client-network

networks:
  oriochat-client-network:
    name: oriochat-client-network
    driver: bridge
